### ISSUE TITLE
The stream start but disconnect after 2 seconds

### ISSUE THREAD

**Issue by dbeiner** [AzuraCast/azurabot#5]
Hello,

When I do `!play 1` the stream start but disconnect after 2 seconds.

Can you help me ? Is there another alternative to Azurabot ?

Thank you !

**Comment by BusterNeece** [comment]
@dbeiner Unfortunately, because we don't have any developers on our team who are particularly proficient with Golang, this project has mostly been abandoned for the last while. It's very likely that Discord's API has changed since the current version of AzuraBot was built, meaning it no longer works properly with Discord.

There are a number of other web-radio-playing Discord bots (including popular ones like Fredboat), and those will work just fine with AzuraCast, although they don't offer the tight integration with our API that our bot does.

We would eagerly welcome any pull requests to improve this project from folks who are more proficient in Golang.

**Comment by dbeiner** [comment]
hello @SlvrEagle23,

Thank you for your answer !

++
